import React, { useState, useEffect } from 'react';

interface Question {
  question: string;
  options: string[];
  correct: number;
  difficulty: 'easy' | 'medium' | 'hard';
}

const Quiz: React.FC = () => {
  const questions: Question[] = [
    {
      question: "Which gas makes up approximately 78% of Earth's atmosphere?",
      options: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
      correct: 2,
      difficulty: "easy"
    },
    {
      question: "What does the term 'biodiversity' refer to?",
      options: ["The variety of life forms in an ecosystem", "The study of living organisms", "The process of evolution", "The classification of species"],
      correct: 0,
      difficulty: "easy"
    },
    {
      question: "Which renewable energy source is generated by the movement of air?",
      options: ["Solar", "Hydroelectric", "Wind", "Geothermal"],
      correct: 2,
      difficulty: "easy"
    },
    {
      question: "What is the primary cause of acid rain?",
      options: ["Nuclear waste", "Sulfur dioxide and nitrogen oxides", "Carbon monoxide", "Methane emissions"],
      correct: 1,
      difficulty: "medium"
    },
    {
      question: "Which layer of the atmosphere contains the ozone layer?",
      options: ["Troposphere", "Stratosphere", "Mesosphere", "Thermosphere"],
      correct: 1,
      difficulty: "medium"
    },
    {
      question: "What is eutrophication?",
      options: ["The process of soil erosion", "Excessive nutrients in water bodies leading to algae growth", "The formation of fossil fuels", "The greenhouse effect"],
      correct: 1,
      difficulty: "medium"
    },
    {
      question: "Which international agreement aims to limit global warming to well below 2°C?",
      options: ["Kyoto Protocol", "Montreal Protocol", "Paris Agreement", "Rio Convention"],
      correct: 2,
      difficulty: "medium"
    },
    {
      question: "What is the concept of 'ecological footprint'?",
      options: ["The size of an animal's paw print", "The measure of human demand on Earth's ecosystems", "The area of a forest", "The depth of soil layers"],
      correct: 1,
      difficulty: "hard"
    },
    {
      question: "Which biome has the highest biodiversity per unit area?",
      options: ["Temperate forests", "Tropical rainforests", "Grasslands", "Deserts"],
      correct: 1,
      difficulty: "hard"
    },
    {
      question: "What is the relationship between albedo and climate change?",
      options: ["Higher albedo surfaces absorb more heat", "Lower albedo surfaces reflect more sunlight", "Albedo has no effect on climate", "Lower albedo surfaces absorb more heat, contributing to warming"],
      correct: 3,
      difficulty: "hard"
    }
  ];

  const [showStartModal, setShowStartModal] = useState(true);
  const [currentQuestion, setCurrentQuestion] = useState(0);
  const [score, setScore] = useState(0);
  const [selectedAnswer, setSelectedAnswer] = useState<number | null>(null);
  const [answered, setAnswered] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [timeLeft, setTimeLeft] = useState(30);
  const [timerActive, setTimerActive] = useState(false);
  const [streak, setStreak] = useState(0);
  const [showFeedback, setShowFeedback] = useState(false);
  const [feedbackMessage, setFeedbackMessage] = useState('');
  const [totalTime, setTotalTime] = useState(0);

  // Timer effect
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (timerActive && timeLeft > 0 && !answered) {
      interval = setInterval(() => {
        setTimeLeft(timeLeft - 1);
      }, 1000);
    } else if (timeLeft === 0 && !answered) {
      setAnswered(true);
      setFeedbackMessage("Time's up! The correct answer is highlighted.");
      setShowFeedback(true);
      setStreak(0);
    }
    return () => clearInterval(interval);
  }, [timerActive, timeLeft, answered]);

  // Total time tracking
  useEffect(() => {
    let interval: NodeJS.Timeout;
    if (!showStartModal && !showResults) {
      interval = setInterval(() => {
        setTotalTime(prev => prev + 1);
      }, 1000);
    }
    return () => clearInterval(interval);
  }, [showStartModal, showResults]);

  const startQuiz = () => {
    setShowStartModal(false);
    setTimerActive(true);
  };

  const selectOption = (index: number) => {
    if (answered) return;
    setSelectedAnswer(index);
  };

  const nextQuestion = () => {
    if (selectedAnswer === null && !answered) return;

    if (!answered) {
      setAnswered(true);
      setTimerActive(false);
      const isCorrect = selectedAnswer === questions[currentQuestion].correct;
      
      if (isCorrect) {
        setScore(score + 1);
        setStreak(streak + 1);
        const timeBonus = timeLeft > 15 ? " Quick answer!" : "";
        setFeedbackMessage(`Correct!${timeBonus}`);
      } else {
        setStreak(0);
        setFeedbackMessage("Incorrect. The correct answer is highlighted.");
      }
      setShowFeedback(true);
      
      setTimeout(() => setShowFeedback(false), 1500);
    } else {
      if (currentQuestion === questions.length - 1) {
        setShowResults(true);
      } else {
        setCurrentQuestion(currentQuestion + 1);
        setSelectedAnswer(null);
        setAnswered(false);
        setTimeLeft(30);
        setTimerActive(true);
      }
    }
  };

  const previousQuestion = () => {
    if (currentQuestion > 0) {
      setCurrentQuestion(currentQuestion - 1);
      setSelectedAnswer(null);
      setAnswered(false);
      setTimeLeft(30);
      setTimerActive(true);
    }
  };

  const restartQuiz = () => {
    setCurrentQuestion(0);
    setScore(0);
    setSelectedAnswer(null);
    setAnswered(false);
    setShowResults(false);
    setShowStartModal(true);
    setTimeLeft(30);
    setTimerActive(false);
    setStreak(0);
    setShowFeedback(false);
    setTotalTime(0);
  };

  const getScoreMessage = () => {
    const percentage = (score / questions.length) * 100;
    const avgTime = Math.round(totalTime / questions.length);
    
    if (percentage >= 90) {
      return `Perfect! Environmental Expert! Average: ${avgTime}s per question`;
    } else if (percentage >= 80) {
      return `Excellent! You're an environmental champion! Average: ${avgTime}s per question`;
    } else if (percentage >= 60) {
      return `Good job! Keep learning about our environment! Average: ${avgTime}s per question`;
    } else if (percentage >= 40) {
      return `Not bad! There's room for improvement! Average: ${avgTime}s per question`;
    } else {
      return `Keep studying! Every expert was once a beginner! Average: ${avgTime}s per question`;
    }
  };

  const progressPercentage = showResults ? 100 : ((currentQuestion + 1) / questions.length) * 100;

  const getDifficultyClass = (difficulty: string) => {
    switch (difficulty) {
      case 'easy': return 'bg-green-100 text-green-700 border border-green-200';
      case 'medium': return 'bg-yellow-100 text-yellow-700 border border-yellow-200';
      case 'hard': return 'bg-red-100 text-red-700 border border-red-200';
      default: return 'bg-gray-100 text-gray-700 border border-gray-200';
    }
  };

  const getTimerColor = () => {
    if (timeLeft > 20) return 'text-green-600';
    if (timeLeft > 10) return 'text-yellow-600';
    return 'text-red-600';
  };

  const getOptionClass = (index: number) => {
    let baseClass = "bg-white border-2 border-gray-200 rounded-lg p-4 cursor-pointer transition-colors duration-200 hover:border-green-400 hover:bg-green-50";
    
    if (selectedAnswer === index && !answered) {
      baseClass += " bg-green-100 border-green-500 text-green-800";
    }
    
    if (answered) {
      baseClass += " cursor-default";
      if (index === questions[currentQuestion].correct) {
        baseClass += " bg-green-100 border-green-500 text-green-800";
      } else if (selectedAnswer === index && index !== questions[currentQuestion].correct) {
        baseClass += " bg-red-100 border-red-500 text-red-800";
      } else {
        baseClass += " opacity-60";
      }
    }
    
    return baseClass;
  };

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 to-emerald-50 flex items-center justify-center p-4">
      {/* Feedback Toast */}
      {showFeedback && (
        <div className="fixed top-4 right-4 bg-white border border-gray-200 rounded-lg shadow-lg p-4 z-50">
          <div className="text-sm font-medium text-gray-800">{feedbackMessage}</div>
        </div>
      )}

      {/* Start Quiz Modal */}
      {showStartModal && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
          <div className="bg-white p-8 rounded-lg text-center max-w-md w-11/12 shadow-xl">
            <div className="text-4xl mb-4">🌱</div>
            <h2 className="text-3xl font-bold text-gray-800 mb-4">Eco Quiz</h2>
            <p className="text-gray-600 mb-6 leading-relaxed">
              Test your knowledge about environmental science and sustainability. 
              You have 30 seconds per question.
            </p>
            <div className="mb-6 p-4 bg-gray-50 rounded-lg">
              <div className="grid grid-cols-3 gap-4 text-center text-sm">
                <div>
                  <div className="font-bold text-lg text-gray-700">10</div>
                  <div className="text-gray-500">Questions</div>
                </div>
                <div>
                  <div className="font-bold text-lg text-gray-700">30s</div>
                  <div className="text-gray-500">Per Question</div>
                </div>
                <div>
                  <div className="font-bold text-lg text-gray-700">3</div>
                  <div className="text-gray-500">Levels</div>
                </div>
              </div>
            </div>
            <button 
              onClick={startQuiz}
              className="bg-green-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-green-700 transition-colors duration-200"
            >
              Start Quiz
            </button>
          </div>
        </div>
      )}

      <div className="max-w-4xl w-full bg-white rounded-lg shadow-lg overflow-hidden">
        {/* Header */}
        <div className="bg-green-600 text-white p-6 text-center">
          <h1 className="text-3xl font-bold mb-2">🌍 Eco Quiz</h1>
          <p className="text-green-100 mb-4">Environmental Studies Assessment</p>
          
          <div className="w-full h-3 bg-green-700 rounded-full overflow-hidden">
            <div 
              className="h-full bg-white rounded-full transition-all duration-500"
              style={{ width: `${progressPercentage}%` }}
            ></div>
          </div>
          <div className="text-sm text-green-100 mt-2">
            Progress: {Math.round(progressPercentage)}%
          </div>
        </div>

        <div className="p-6">
          {!showResults ? (
            <>
              {/* Question Header */}
              <div className="flex justify-between items-center mb-6 flex-wrap gap-4">
                <div className="flex items-center gap-3">
                  <div className="bg-green-100 text-green-700 px-4 py-2 rounded-full font-semibold">
                    Question {currentQuestion + 1} of {questions.length}
                  </div>
                  {streak > 1 && (
                    <div className="bg-orange-100 text-orange-700 px-3 py-1 rounded-full text-sm font-semibold">
                      {streak} streak
                    </div>
                  )}
                </div>
                
                <div className="flex items-center gap-4">
                  <div className={`px-3 py-1 rounded-full text-sm font-semibold ${getDifficultyClass(questions[currentQuestion].difficulty)}`}>
                    {questions[currentQuestion].difficulty.toUpperCase()}
                  </div>
                  
                  <div className={`text-xl font-bold ${getTimerColor()}`}>
                    {timeLeft}s
                  </div>
                </div>
              </div>

              {/* Question */}
              <div className="text-2xl font-semibold text-gray-800 mb-6 leading-relaxed">
                {questions[currentQuestion].question}
              </div>

              {/* Options */}
              <div className="grid gap-3 mb-6">
                {questions[currentQuestion].options.map((option, index) => (
                  <div
                    key={index}
                    onClick={() => selectOption(index)}
                    className={getOptionClass(index)}
                  >
                    <div className="flex items-center justify-between">
                      <span>{option}</span>
                      {answered && index === questions[currentQuestion].correct && (
                        <span className="text-green-600">✓</span>
                      )}
                      {answered && selectedAnswer === index && index !== questions[currentQuestion].correct && (
                        <span className="text-red-600">✗</span>
                      )}
                    </div>
                  </div>
                ))}
              </div>

              {/* Navigation Buttons */}
              <div className="flex justify-between gap-4">
                <button
                  onClick={previousQuestion}
                  className={`px-6 py-3 rounded-lg font-semibold transition-colors duration-200 ${
                    currentQuestion === 0 
                      ? 'invisible' 
                      : 'bg-gray-200 text-gray-700 hover:bg-gray-300'
                  }`}
                >
                  Previous
                </button>
                <button
                  onClick={nextQuestion}
                  disabled={selectedAnswer === null && !answered}
                  className="bg-green-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-green-700 transition-colors duration-200 disabled:opacity-50 disabled:cursor-not-allowed"
                >
                  {answered 
                    ? (currentQuestion === questions.length - 1 ? 'Show Results' : 'Next Question')
                    : 'Submit Answer'
                  }
                </button>
              </div>
            </>
          ) : (
            /* Results */
            <div className="text-center py-8">
              <div className="text-6xl mb-4">
                {score >= 8 ? '🏆' : score >= 6 ? '🌟' : score >= 4 ? '🌱' : '📚'}
              </div>
              <div className="text-5xl font-bold text-green-600 mb-4">
                {score}/{questions.length}
              </div>
              <div className="text-lg text-gray-600 mb-8 max-w-lg mx-auto">
                {getScoreMessage()}
              </div>
              
              {/* Stats */}
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8 max-w-lg mx-auto">
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-2xl font-bold text-gray-700">{Math.round((score/questions.length)*100)}%</div>
                  <div className="text-gray-500 text-sm">Accuracy</div>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-2xl font-bold text-gray-700">{formatTime(totalTime)}</div>
                  <div className="text-gray-500 text-sm">Total Time</div>
                </div>
                <div className="bg-gray-50 p-4 rounded-lg">
                  <div className="text-2xl font-bold text-gray-700">{streak > 0 ? streak : '-'}</div>
                  <div className="text-gray-500 text-sm">Best Streak</div>
                </div>
              </div>
              
              <button
                onClick={restartQuiz}
                className="bg-green-600 text-white px-6 py-3 rounded-lg font-semibold hover:bg-green-700 transition-colors duration-200"
              >
                Take Quiz Again
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default Quiz;